### ISSUE TITLE
Variable 'version' needs fix

### ISSUE THREAD

**Issue by kaunteya** [ChimeHQ/Neon#13]
Version variable is always assigned to zero and does not have any effect.

[https://github.com/ChimeHQ/Neon/pull/11#issuecomment-1229479196](https://github.com/ChimeHQ/Neon/pull/11#issuecomment-1229479196)

**Comment by mattmassicotte** [comment]
This is a great report. I **think** this was accidentally removed while I was migrating code from Chime to Neon. It is essential, because it's very easy for state to get out of sync with the text. And, that has to be carefully tracked to avoid accessing old and invalid ranges/content.

**Comment by mattmassicotte** [comment]
I've addressed this with #[9314406](https://github.com/ChimeHQ/Neon/commit/9314406d716878bbde2296447747f4b3d5a9dbca)
