### ISSUE TITLE
Crash on async access

### ISSUE THREAD

**Issue by kaunteya** [ChimeHQ/Neon#22]
Crash happens on async access to `currentTree`

Created a minimum reproducible [https://github.com/kaunteya/TreeSitter-crash-minreprex](https://github.com/kaunteya/TreeSitter-crash-minreprex)

**Comment by mattmassicotte** [comment]
Ok I will look closer tomorrow. But I just looked quickly. It seems that the node instance is outliving the tree it is a part of. If you keep references to both (could just quickly return a tuple) does it help?

**Comment by kaunteya** [comment]
Yes. That was quick Matt. Thanks!!
