### ISSUE TITLE
'staleContent' error in highlighter

### ISSUE THREAD

**Issue by kaunteya** [ChimeHQ/Neon#23]
I am getting an error while updating the font size of textview
```swift
self.textView.font = .systemFont(ofSize: size, weight: .regular)
```

The error says `failed to get tokens:  staleContent`

----
Tried debugging and noticed that the issue does not occur in the Example project. While comparing the stack side by side by putting breakpoints on the line which prints error, it seems like the guard comparison fails on the following line

https://github.com/ChimeHQ/Neon/blob/4bc0fe43c46e2c08cf522d5db86666086b6e641e/Sources/TreeSitterClient/TreeSitterClient.swift#L350

In debugger startedVersion = 2 and self.version = 3. What could be the probable reason? 
The code works fine despite the error

**Comment by kaunteya** [comment]
Turns out, the issue was due to font getting assigned twice in quick succession.
https://stackoverflow.com/questions/65965666/why-does-user-defaults-publisher-trigger-multiple-times

**Comment by kaunteya** [comment]
Will it make sense to call `treeSitterClient.willChangeContent` and `treeSitterClient.didChangeContent` only when edited mask contains `editedCharacters`?

```swift
    func textStorage(_ textStorage: NSTextStorage, willProcessEditing editedMask: NSTextStorageEditActions, range editedRange: NSRange, changeInLength delta: Int) {
        if editedMask.contains(.editedCharacters) {
            treeSitterClient.willChangeContent(in: editedRange)
        }
    }

    func textStorage(_ textStorage: NSTextStorage, didProcessEditing editedMask: NSTextStorageEditActions, range editedRange: NSRange, changeInLength delta: Int) {
        guard editedMask.contains(.editedCharacters) else { return }
        let adjustedRange = NSRange(location: editedRange.location, length: editedRange.length - delta)
        let string = textStorage.string

        highlighter.didChangeContent(in: adjustedRange, delta: delta)
        treeSitterClient.didChangeContent(to: string, in: adjustedRange, delta: delta, limit: string.utf16.count)

```

**Comment by mattmassicotte** [comment]
I *think* it is safe to ignore edits if they only contain attribute changes. But, I have experimented with this in the past and have run into issues - I just cannot remember why...
