### ISSUE TITLE
Coalesce attribute changes into one block

### ISSUE THREAD

**Issue by DivineDominion** [ChimeHQ/Neon#32]
I noticed that multiple changes to the attributes during the same edit operation aren't batched up.

See:

1. [`beginEditing`](https://developer.apple.com/documentation/foundation/nsmutableattributedstring/1411853-beginediting#)
2. (apply styles here, potentially nesting calls)
3. [`endEditing`](https://developer.apple.com/documentation/foundation/nsmutableattributedstring/1416707-endediting)

Once the outermost pair of these calls finishes, delegates and the layout manager are notified.

`TextSystemInterface.applyStyles(to:)` loops over all tokens in a batch and applies them to the text. This would reduce `NSTextStorageDelegate` callbacks a lot already if we wrap the loop in begin/end editing calls.

But when pasting longer parts of text, `applyStyles(to:)` is called multiple times. I believe the architecture around that is mostly to support asynchronous highlighting?

So -- I don't yet see a way to make e.g. pasting the whole `Highlighter.swift` file into the sample app produce only one such delegate x (and layout manager) callback.

@mattmassicotte Would you still be interested in batch-processing changes? If so, I'm not sure how to best model this 🤔  Suggestions:

- Add a function to the `TextSystemInterface` protocol like `groupStyleChanges(_ unitOfWork: () -> Void)` and surround the for-in-loop. `TextViewSystemInterface` would need to provide the implementation, then, because it has access to the text storage.
- Send notifications before/after the loop instead. Would not match the rest of the architecture IMHO.
- Execute (optional?) begin/end functions instead. Could also be closure properties of the `TextSystemInterface` protocol. Would require 2 functions or 2 properties, though, and IMHO that's a weird amount of API surface . Also conforming types need to declare stored properties, so it's also annoying :)

**Comment by mattmassicotte** [comment]
I cannot recall when this came up last, but yes, this is a limitation that should definitely be addressed. I appreciate you laying out all the options here.

I'm definitely leaning towards a block-based solution, but I have to think a little harder.

**Comment by mattmassicotte** [comment]
While I'm sure this helps you specifically, the main branch includes a solution for this.

`TextSystemInterface` now uses a higher-level abstraction that provides complete control over the entire process via `func applyStyles(for application: TokenApplication)`. It (currently) makes for a little more code duplication, but is much more general-purpose.
