### ISSUE TITLE
SwiftUI example

### ISSUE THREAD

**Issue by keyle** [ChimeHQ/Neon#36]
Hi there,

Is there a SwiftUI example project? 

I'm having difficulties to get going with this. I'm using a NSTextViewDelegate in a SwiftUI project.

Any help appreciated.

**Comment by mattmassicotte** [comment]
I'm so glad you reached out - I would be very happy to help!

I hope the read me was clear, but Neon isn't a drop-in view. It is a collection of components you can use for efficient text style application and invalidation. So, how you integrate it it very dependent on your text system and what you are trying to do.

(I'm actually working right now on further generalizing the system and adopting Swift concurrency!)

Are you wrapping up an NSTextView for use in SwiftUI? And are you interested in using tree-sitter for token information, or some other source? You may want to have a look at `TextViewHighlighter`. It is easiest (but least-flexible) option for directly connecting tree-sitter to an NSTextView.

**Comment by mattmassicotte** [comment]
(I also just put a link to a Discord in case you are looking for some more live help and that's your kind of thing)

**Comment by keyle** [comment]
Thanks, I've seen and corrected a mistake of mine.

I had added `neon` to my project via the add package... Only did it add `0.5.1` by default and that was missing some classes, as it's 7 months old. So that got me confused for a while. 

I understand Swift well, but as a polyglot, I'm not really across XCode. Changing that to "branch" "main" fixed the missing class issues.

The other problem I'm having is with the bundle business 
```
let url = Bundle.main
	  .resourceURL?
	  .appendingPathComponent("TreeSitterSwift_TreeSitterSwift.bundle")
	  .appendingPathComponent("queries/highlights.scm")
let query = try! language.query(contentsOf: url!)
```

Would it be possible to see a full example with `tree_sitter_c` or other language that has a clear cut away from Swift without this bundle business? 

For the sake of not tip toeing around and this thread carrying on, which is due to my lack of understanding, I've included the code I'm haplessly trying to adapt for a code editor: https://gist.github.com/keyle/228ffd4a5622c1c328299f3ff9dd7c25 

I've highlighter the issue at `problem here`.

Thanks for your time 🙏🏻

**Comment by mattmassicotte** [comment]
What wasn't working with 0.5.1? That's definitely supposed to be functional.

The bundle handling is completely independent of parser language. The issue is you must provide the tree-sitter integration with a minimum of two things: the parser and the highlighting query patterns. Many tree-sitter parsers have been packaged up with SPM to ease integration into Swift code.

Your code isn't working because you have added "TreeSitterC", but you are telling the system to look for a bundle called "TreeSitterSwift". Try this:

```swift
let url = Bundle.main
            .resourceURL?
            .appendingPathComponent("TreeSitterC_TreeSitterC.bundle")
            .appendingPathComponent("Contents/Resources/queries/highlights.scm")
        let query = try! language.query(contentsOf: url!)
```

Another alternative is to make use of the bundle searching facilities in SwiftTreeSitter (this is the runtime system, not to be confused with the Swift language parser called TreeSitterSwift).

(writing this off the top of my head, could be wrong)

```swift
let language = Language(language: tree_sitter_c(), name: "C")
let query = try! language.query(contentsOf: language.highlightsFileURL!)
```

**Comment by mattmassicotte** [comment]
Any progress?

**Comment by keyle** [comment]
Sorry for the lack of updates, life got in the way... What you've written makes sense and clearly I wasn't groking the relationship with the bundle and tree sitter.

**Comment by mattmassicotte** [comment]
Absolutely no need to apologize. If anything else comes up, please don't be shy to ask again!
